---
- name: configure apache2 webserver; install, change content of index.html, restart apache2
  hosts: dev
  tasks:
   - name: install apache2
     apt:
      name: apache2
      state: present
      update_cache: yes
   - name: change the content of index.html 
     copy:
      content: "Hello world, welcome to ansible sessions. This is Playbook NO.3"
      dest: /var/www/html/index.html
   - name: restart apache2
     service:
      name: apache2
      state: restarted
...
