---
- name: error handling in ansible
  hosts: all
  tasks:
   - block: 
      - name: install tomcat7
        apt:
         name: tomcat7
         state: present
         update_cache: yes
     rescue:
      - name: install tomcat9
        apt:
         name: tomcat9
         state: present
         update_cache: yes
     always:
      - name: install tomcat8
        apt: 
         name: tomcat8
         state: present
         update_cache: yes
